### ISSUE TITLE
Issue with OSD on hover

### ISSUE THREAD

**Issue by Qwerty-Space** [SilverEzhik/umpvw#3]
Idk if this is an mpv, or umpvw issue, but the OSD that shows up on hovering stops working after a couple of videos have played in the same instance.

**Comment by Qwerty-Space** [comment]
Additionally, will this be updated to the latest mpv version?

**Comment by SilverEzhik** [comment]
Hmm, I never ran into this problem. Also, this doesn't actually include mpv - to update the player itself, just replace actual mpv.exe and such in the folder. Unless mpv developers change how IPC works, there should not be any issues.

**Comment by Qwerty-Space** [comment]
Correction, it's actually the OSC I'm referring to.

**Comment by Qwerty-Space** [comment]
And, so umpvw doesn't have its own modified mpv executable?

**Comment by SilverEzhik** [comment]
No. It's just the normal mpv.

**Comment by Qwerty-Space** [comment]
Oh 🤔 
Where are the changes made then?

**Comment by SilverEzhik** [comment]
There are no changes made. umpvw works by communicating with an existing mpv instance through IPC, or by starting a new one, if one is not detected.
